### ISSUE TITLE
Support for Slack

### ISSUE THREAD

**Issue by littke** [lookback/meteor-seo#5]
Slack [say](https://api.slack.com/robots) they're looking for oEmbed, Twitter Cards or OpenGraph tags on a page when expanding links in the chat room. But it appears not to be working with Lookback URLs (that uses this package, naturally ;-)).

Any ideas?

**Comment by littke** [comment]
It works on Twitter:

https://www.dropbox.com/s/7xhoprwxiigwvy8/Screenshot%202015-05-17%2019.30.13.png?dl=0

**Comment by johanbrook** [comment]
> [..] that uses this package, naturally.

Actually, no. We haven't upgraded to PhantomJS 2.0 (as stated as dependency in the README) yet, so we use an older version of this package, internally. Thanks for filing!

I should have a look why the SEO props don't render with PhantomJS 1.x installed. Even meteor.com hasn't PhantomJS 2.0 yet (sample app for testing available at: http://router-seo.meteor.com/).

**Comment by johanbrook** [comment]
@littke After some investigation, it seems it's Slack who is the crook here! (Spiderable too, partly).

In the Spiderable source, we [can read this](https://github.com/meteor/meteor/blob/9e2539bcd139242ba09b915ec80096111099f852/packages/spiderable/spiderable_server.js#L6-L16):

```js
// list of bot user agents that we want to serve statically, but do
// not obey the _escaped_fragment_ protocol. The page is served
// statically to any client whos user agent matches any of these
// regexps. Users may modify this array.
//
// An original goal with the spiderable package was to avoid doing
// user-agent based tests. But the reality is not enough bots support
// the _escaped_fragment_ protocol, so we need to hardcode a list
// here. I shed a silent tear.
Spiderable.userAgentRegExps = [
    /^facebookexternalhit/i, /^linkedinbot/i, /^twitterbot/i];
```

So it seems Slack isn't crawling with the standard `?_escaped_fragment_` query parameter, and since it's not included in Spiderable's list of user agents, Spiderable won't kick in :(

I can't find *anything* on google on Slack's link crawling either. I'll ping Slack to see what's up.

**Comment by littke** [comment]
@johanbrook Is this what you're looking for? 

https://api.slack.com/docs/unfurling

Also, Discourse has the same behavior. Can we modify the list of userAgents in Spiderable on our own?

**Comment by johanbrook** [comment]
@littke I read that, it's sadly unrelated to this.

> Can we modify the list of userAgents in Spiderable on our own?

Yep, I thought of that, and I guess we can do that for now. It's no other way around this, unless the Slack devs respond with some info.

**Comment by johanbrook** [comment]
Also: https://twitter.com/slackapi/status/625704700575379456

> We currently don't support it, but we are looking into it. Thanks for the link!
> @slackAPI

**Comment by johanbrook** [comment]
Posted issue in Meteor's repo for Spiderable:

https://github.com/meteor/meteor/issues/4830

**Comment by stackswell** [comment]
I've poured an unfortunate number of hours into resolving this issue, so I figured perhaps my experiences may bring insight, or perhaps someone has had a similar tale of events. Unfortunately, up until a few weeks ago Slack was reading our meta data just fine. At the time we were running `gadicohen:phantomjs` along with the standard `spiderable` package and `DerMambo:ms-seo`. Upon configuring Cloudflare and effectively ssl, we ran into internal server errors with our escaped fragment.
Since then, we have had to switch to using dfischer:phantomjs with ongoworks:spiderable in order to get the escaped fragment to behave correctly, and in the process we have lost meta recognition on both slack and reddit. Still works just fine on facebook and twitter. I simply can't figure out what has changed resulting in the abrupt change in behavior, particularly since we get the same results testing our build on `onmodulus.net` bypassing cloudflare's proxy entirely. At this point it remains a mystery to me.

 > Note: we are using Modulus, which has notoriously had issues with Meteor fibers and phantom js, largely in part due to the docker container, however, everything was working properly a mere matter of weeks ago.

**Comment by johanbrook** [comment]
Hey @stackswell, thanks for chiming in. We too have experienced troubles with Spiderable/Phantom during the past couple of weeks, incidentally coincided with a refactor to move to FlowRouter instead of Iron Router :)

I really think MDG should start thinking of a more robust solution for doing SEO and supporting server side rendering or similar.
